# Generated by Django 5.0 on 2023-12-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_remove_manager_dept_remove_employee_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
