# Generated by Django 5.0 on 2023-12-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0007_alter_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
