# Generated by Django 5.0 on 2023-12-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0008_remove_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default='0000000', max_length=1000, null=True),
        ),
    ]
