# Generated by Django 5.0 on 2023-12-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0009_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cisco_id',
            field=models.CharField(default='cisco_id', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='Status', max_length=1000, null=True),
        ),
    ]
